### ISSUE TITLE
speedometer speed is never 0

### ISSUE THREAD

**Issue by linuxgurugamer** [linuxgurugamer/KerbalSmartParts#11]
Need to add a simple 2 digit roundoff

**Comment by linuxgurugamer** [comment]
needed both for display and detection

**Comment by rakkhin** [comment]
Patch included (github doesn't like path files).
[Speedometer.patch.txt](https://github.com/linuxgurugamer/KerbalSmartParts/files/908151/Speedometer.patch.txt)

**Comment by linuxgurugamer** [comment]
thanks, I added it after merging your other PRs
