### ISSUE TITLE
Sometimes sensors are activated on first staging

### ISSUE THREAD

**Issue by Gordon-Dry** [linuxgurugamer/KerbalSmartParts#19]
I had several occasions that sensors that should fire an action group on decreasing tank resources already fired directly at launch staging.

I use this workaround actually:
All sensors are deactivated and will be activated by an additional altimeter sensor at a low altitude like 2km.

**Comment by linuxgurugamer** [comment]
Please post a craft file which this happens on.  Also a log file.

**Comment by linuxgurugamer** [comment]
Closing as no further information was posted
