### ISSUE TITLE
Enhancement: Specific ullage-with-RCS-smart-part for RealFuels / RealismOverhaul

### ISSUE THREAD

**Issue by Gordon-Dry** [linuxgurugamer/KerbalSmartParts#20]
How about a smart part, that can enable (powerful) RCS thrusters that are only used for ullage?

This part should only be available when RealismOverhaul and RealFuels are installed.
(Fuel stability seems not to be an issue when RealFuels is installed on stock without RO).

It should be attached to the engine somehow, so it should be a narrow stackable part (in different sizes or resizeable without the need of TweakScale) that sits above the engine.

It could (should?) somehow work with SolverEngines and when the engine should be ignited then first the Smart part should kick in, disable the engine, change RCS to "Fore by throttle" and "Always full action", enable RCS and thrust up, then enable the engine that was meant to be throttled up.

When the acceleration is growing, so the engine works, reset RCS to previous settings / state.

This would be interesting for later ignitions, when no more solid fuel ullage booster is available.

**Comment by linuxgurugamer** [comment]
I don't do mods which don't run in stock.  
This really sounds like something that should be it's own mod.  From what you describe, it's going to be somewhat involved to do.
