### ISSUE TITLE
Action Groups Extended

### ISSUE THREAD

**Issue by sick13** [linuxgurugamer/KerbalSmartParts#21]
Displays message in Editor when part is picked up

ADDON BINDER: Cannot resolve assembly: AGExt, Culture=neutral, PublicKeyToken=null

**Comment by linuxgurugamer** [comment]
Details, such as KSP version, AGEXT version, smart parts version, log file are needed

**Comment by linuxgurugamer** [comment]
Closing as no further informatin was provided
