### ISSUE TITLE
Part request: suicide burn trigger

### ISSUE THREAD

**Issue by mLuby** [linuxgurugamer/KerbalSmartParts#28]
This might be complicated but it'd be awesome for simple propulsive landings. Alternatively could be wrapped into the altimeter sensor since it is kind of a height thing.

It's currently possible to get a controlled descent with the -10m/s velocity sensor activating retro-rockets until the downward velocity is under control, then another -5m/s velocity sensor deactivates them. But then you just get retro-rockets pulsing to keep your craft descending around 8m/s. Super inefficient compared to a suicide burn.

I imagine the difficult part here is figuring out the activated engine(s) thrust and burn time. Kerbal Engineer, MJ, and kOS all seem to be able to do it.

**Comment by linuxgurugamer** [comment]
Sorry, not going to happen.

It's too complicated for this part.  There are too many variables involved
