### ISSUE TITLE
SmartSRB should inherit from SmartSensorModuleBase

### ISSUE THREAD

**Issue by Thorbane** [linuxgurugamer/KerbalSmartParts#30]
What the title says.  Currently displays no UI other than the TWR slider.

Currently inherits from directly from PartModule.

**Comment by linuxgurugamer** [comment]
Why?  That's all it needs, the SmartSensorModuleBase adds in three other sliders which aren't needed

**Comment by Thorbane** [comment]
I thought the lack of action group capability was a bug.  Why shouldn't it be capable of firing an action group instead of staging?  I've always found action groups more reliable and versatile than the stage command.  For Smart Parts especially, as you don't need to worry about what order things happen in.

**Comment by linuxgurugamer** [comment]
Fixed in current release
