### ISSUE TITLE
Resource detection on vessel

### ISSUE THREAD

**Issue by linuxgurugamer** [linuxgurugamer/KerbalSmartParts#5]
No, but it's a great idea.

Rather than make it specific to EC, I'll write one which will do the following:

Detect when a specified resource is less than or greater than a specified value
Fire action group upon detection
In order to do this, I need two things, looking for a volunteer:

First, a name for this, "Resource Pro" for now, but would like a better name
Someone to make a part for this

**Comment by ChristianH181** [comment]
How about "LDM" (level detection module)? Need the module urgently for my Moho ground station.
For the part you can not take the standard parts with new texture?

I hope the english is not too bad ... Google translator, come from germany :)

**Comment by linuxgurugamer** [comment]
Very soon, thanks

**Comment by linuxgurugamer** [comment]
Releasing it now
