### ISSUE TITLE
Better control of altimeter

### ISSUE THREAD

**Issue by linuxgurugamer** [linuxgurugamer/KerbalSmartParts#9]
On the altimeter, there should be two bars for the height: one in km, one in meters (with 100m increment), plus an editable field for entering the value manually. Would simplify & enhance the thing. There is no way to trigger an action group around 1500m for now. Or I didn't find it.

**Comment by BenjaminCronin** [comment]
Could you do something like this?
If (vessel.height >= 1500)
{ actionGroup1 = true) }

**Comment by linuxgurugamer** [comment]
Not sure what you mean, it can already trigger an actiion group

**Comment by BenjaminCronin** [comment]
Oh, ok. Just saying becasue the issue was still open
